# Generated by Django 4.2.3 on 2023-07-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_here',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
